### ISSUE TITLE
writeExif for Dng

### ISSUE THREAD

**Issue by sygslhy** [emmcb/cxx-image#5]
Hello, 
I just notice that we don't have the writeExif API for  DNG in IO library.
is it possible to do this in short time?
because in the README.md of IO have a Exif = "x" in DNG. or we just need to remove it from the table?

**Comment by emmcb** [comment]
Hi, writeExif is not supported for DNG currently, however EXIF have a "x" in the readme because you can still read and write the EXIFs when reading and writing a DNG image.
It should be doable to support this, however:

- I do not think it would be much useful in this form, what you want for DNG is generally to update metadata fields like color matrix or gain maps, thus a more generic writeMetadata would be needed.
- writeExif API is really important for lossy compression formats like jpeg because it allows to update the EXIFs without re-encoding the image (which would lose information). For lossless formats reading and re-writing is slower, but ok image-side.
